name: 'Artifactory'
description: 'Yep This is how we do it'
inputs:
  artifactory-password:  # id of input
    description: 'Artifactory Password'
    required: true
    default: 'required'
  artifactory-username:  # id of input
    description: 'Artifactory User Name'
    required: true
    default: 'required'
  artifactory-docker-url:  # id of input
    description: 'Docker Repo URL'
    required: true
    default: 'qliktech-docker-infrastructure.jfrog.io'
outputs:
  time: # id of output
    description: 'Docker Artifactory Login'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.artifactory-username }}
    - ${{ inputs.artifactory-password }}
    - ${{ inputs.artifactory-docker-url }}